/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SpacePoolMonitor.ApiClient.Client.OpenAPIDateConverter;

namespace SpacePoolMonitor.ApiClient.Model
{
    /// <summary>
    /// Confirmation status of the block
    /// </summary>
    /// <value>Confirmation status of the block</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BlockConfirmationStatusV1
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum Maturing for value: Maturing
        /// </summary>
        [EnumMember(Value = "Maturing")]
        Maturing = 2,

        /// <summary>
        /// Enum Confirmed for value: Confirmed
        /// </summary>
        [EnumMember(Value = "Confirmed")]
        Confirmed = 3,

        /// <summary>
        /// Enum Reverted for value: Reverted
        /// </summary>
        [EnumMember(Value = "Reverted")]
        Reverted = 4

    }

}
