/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SpacePoolMonitor.ApiClient.Client.OpenAPIDateConverter;

namespace SpacePoolMonitor.ApiClient.Model
{
    /// <summary>
    /// Confirmation status of the payout transaction
    /// </summary>
    /// <value>Confirmation status of the payout transaction</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PayoutStatusV1
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum Unconfirmed for value: Unconfirmed
        /// </summary>
        [EnumMember(Value = "Unconfirmed")]
        Unconfirmed = 2,

        /// <summary>
        /// Enum Confirmed for value: Confirmed
        /// </summary>
        [EnumMember(Value = "Confirmed")]
        Confirmed = 3

    }

}
