/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SpacePoolMonitor.ApiClient.Client.OpenAPIDateConverter;

namespace SpacePoolMonitor.ApiClient.Model
{
    /// <summary>
    /// Generic response model for requests that have pageable collections
    /// </summary>
    [DataContract(Name = "PayoutV1ModelPagedCollectionResponseV1Model")]
    public partial class PayoutV1ModelPagedCollectionResponseV1Model : IEquatable<PayoutV1ModelPagedCollectionResponseV1Model>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayoutV1ModelPagedCollectionResponseV1Model" /> class.
        /// </summary>
        /// <param name="results">API response results.</param>
        /// <param name="continuationToken">Continuation token for resuming paging of the previous request.</param>
        public PayoutV1ModelPagedCollectionResponseV1Model(List<PayoutV1Model> results = default(List<PayoutV1Model>), string continuationToken = default(string))
        {
            this.Results = results;
            this.ContinuationToken = continuationToken;
        }

        /// <summary>
        /// API response results
        /// </summary>
        /// <value>API response results</value>
        [DataMember(Name = "results", EmitDefaultValue = true)]
        public List<PayoutV1Model> Results { get; set; }

        /// <summary>
        /// Continuation token for resuming paging of the previous request
        /// </summary>
        /// <value>Continuation token for resuming paging of the previous request</value>
        [DataMember(Name = "continuationToken", EmitDefaultValue = true)]
        public string ContinuationToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PayoutV1ModelPagedCollectionResponseV1Model {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  ContinuationToken: ").Append(ContinuationToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PayoutV1ModelPagedCollectionResponseV1Model);
        }

        /// <summary>
        /// Returns true if PayoutV1ModelPagedCollectionResponseV1Model instances are equal
        /// </summary>
        /// <param name="input">Instance of PayoutV1ModelPagedCollectionResponseV1Model to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PayoutV1ModelPagedCollectionResponseV1Model input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Results == input.Results ||
                    this.Results != null &&
                    input.Results != null &&
                    this.Results.SequenceEqual(input.Results)
                ) && 
                (
                    this.ContinuationToken == input.ContinuationToken ||
                    (this.ContinuationToken != null &&
                    this.ContinuationToken.Equals(input.ContinuationToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Results != null)
                {
                    hashCode = (hashCode * 59) + this.Results.GetHashCode();
                }
                if (this.ContinuationToken != null)
                {
                    hashCode = (hashCode * 59) + this.ContinuationToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
