/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockV1Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockV1ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockV1Model
        //private BlockV1Model instance;

        public BlockV1ModelTests()
        {
            // TODO uncomment below to create an instance of BlockV1Model
            //instance = new BlockV1Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockV1Model
        /// </summary>
        [Fact]
        public void BlockV1ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockV1Model
            //Assert.IsType<BlockV1Model>(instance);
        }


        /// <summary>
        /// Test the property 'LuckPercent'
        /// </summary>
        [Fact]
        public void LuckPercentTest()
        {
            // TODO unit test for the property 'LuckPercent'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'RewardInXCH'
        /// </summary>
        [Fact]
        public void RewardInXCHTest()
        {
            // TODO unit test for the property 'RewardInXCH'
        }
        /// <summary>
        /// Test the property 'CreationDateTimeUtc'
        /// </summary>
        [Fact]
        public void CreationDateTimeUtcTest()
        {
            // TODO unit test for the property 'CreationDateTimeUtc'
        }
        /// <summary>
        /// Test the property 'WinnerLauncherId'
        /// </summary>
        [Fact]
        public void WinnerLauncherIdTest()
        {
            // TODO unit test for the property 'WinnerLauncherId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
