/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockConfirmationStatusV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockConfirmationStatusV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockConfirmationStatusV1
        //private BlockConfirmationStatusV1 instance;

        public BlockConfirmationStatusV1Tests()
        {
            // TODO uncomment below to create an instance of BlockConfirmationStatusV1
            //instance = new BlockConfirmationStatusV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockConfirmationStatusV1
        /// </summary>
        [Fact]
        public void BlockConfirmationStatusV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockConfirmationStatusV1
            //Assert.IsType<BlockConfirmationStatusV1>(instance);
        }



    }

}
