/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PartialV1Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartialV1ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartialV1Model
        //private PartialV1Model instance;

        public PartialV1ModelTests()
        {
            // TODO uncomment below to create an instance of PartialV1Model
            //instance = new PartialV1Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartialV1Model
        /// </summary>
        [Fact]
        public void PartialV1ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartialV1Model
            //Assert.IsType<PartialV1Model>(instance);
        }


        /// <summary>
        /// Test the property 'LauncherId'
        /// </summary>
        [Fact]
        public void LauncherIdTest()
        {
            // TODO unit test for the property 'LauncherId'
        }
        /// <summary>
        /// Test the property 'HarvesterId'
        /// </summary>
        [Fact]
        public void HarvesterIdTest()
        {
            // TODO unit test for the property 'HarvesterId'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Difficulty'
        /// </summary>
        [Fact]
        public void DifficultyTest()
        {
            // TODO unit test for the property 'Difficulty'
        }
        /// <summary>
        /// Test the property 'SubmissionDateTimeUtc'
        /// </summary>
        [Fact]
        public void SubmissionDateTimeUtcTest()
        {
            // TODO unit test for the property 'SubmissionDateTimeUtc'
        }

    }

}
