/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PartialV1ModelCollectionResponseV1Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartialV1ModelCollectionResponseV1ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartialV1ModelCollectionResponseV1Model
        //private PartialV1ModelCollectionResponseV1Model instance;

        public PartialV1ModelCollectionResponseV1ModelTests()
        {
            // TODO uncomment below to create an instance of PartialV1ModelCollectionResponseV1Model
            //instance = new PartialV1ModelCollectionResponseV1Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartialV1ModelCollectionResponseV1Model
        /// </summary>
        [Fact]
        public void PartialV1ModelCollectionResponseV1ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartialV1ModelCollectionResponseV1Model
            //Assert.IsType<PartialV1ModelCollectionResponseV1Model>(instance);
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
