/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PayoutV1Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayoutV1ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayoutV1Model
        //private PayoutV1Model instance;

        public PayoutV1ModelTests()
        {
            // TODO uncomment below to create an instance of PayoutV1Model
            //instance = new PayoutV1Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayoutV1Model
        /// </summary>
        [Fact]
        public void PayoutV1ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayoutV1Model
            //Assert.IsType<PayoutV1Model>(instance);
        }


        /// <summary>
        /// Test the property 'LauncherId'
        /// </summary>
        [Fact]
        public void LauncherIdTest()
        {
            // TODO unit test for the property 'LauncherId'
        }
        /// <summary>
        /// Test the property 'CoinId'
        /// </summary>
        [Fact]
        public void CoinIdTest()
        {
            // TODO unit test for the property 'CoinId'
        }
        /// <summary>
        /// Test the property 'ConfirmationBlockNumber'
        /// </summary>
        [Fact]
        public void ConfirmationBlockNumberTest()
        {
            // TODO unit test for the property 'ConfirmationBlockNumber'
        }
        /// <summary>
        /// Test the property 'FeeInXCH'
        /// </summary>
        [Fact]
        public void FeeInXCHTest()
        {
            // TODO unit test for the property 'FeeInXCH'
        }
        /// <summary>
        /// Test the property 'PayoutBalanceInXCH'
        /// </summary>
        [Fact]
        public void PayoutBalanceInXCHTest()
        {
            // TODO unit test for the property 'PayoutBalanceInXCH'
        }
        /// <summary>
        /// Test the property 'PayoutDateTimeUtc'
        /// </summary>
        [Fact]
        public void PayoutDateTimeUtcTest()
        {
            // TODO unit test for the property 'PayoutDateTimeUtc'
        }
        /// <summary>
        /// Test the property 'RecipientPuzzleHash'
        /// </summary>
        [Fact]
        public void RecipientPuzzleHashTest()
        {
            // TODO unit test for the property 'RecipientPuzzleHash'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
