/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PayoutV1ModelPagedCollectionResponseV1Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayoutV1ModelPagedCollectionResponseV1ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayoutV1ModelPagedCollectionResponseV1Model
        //private PayoutV1ModelPagedCollectionResponseV1Model instance;

        public PayoutV1ModelPagedCollectionResponseV1ModelTests()
        {
            // TODO uncomment below to create an instance of PayoutV1ModelPagedCollectionResponseV1Model
            //instance = new PayoutV1ModelPagedCollectionResponseV1Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayoutV1ModelPagedCollectionResponseV1Model
        /// </summary>
        [Fact]
        public void PayoutV1ModelPagedCollectionResponseV1ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayoutV1ModelPagedCollectionResponseV1Model
            //Assert.IsType<PayoutV1ModelPagedCollectionResponseV1Model>(instance);
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'ContinuationToken'
        /// </summary>
        [Fact]
        public void ContinuationTokenTest()
        {
            // TODO unit test for the property 'ContinuationToken'
        }

    }

}
