/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PoolInfoV1Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PoolInfoV1ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PoolInfoV1Response
        //private PoolInfoV1Response instance;

        public PoolInfoV1ResponseTests()
        {
            // TODO uncomment below to create an instance of PoolInfoV1Response
            //instance = new PoolInfoV1Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PoolInfoV1Response
        /// </summary>
        [Fact]
        public void PoolInfoV1ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PoolInfoV1Response
            //Assert.IsType<PoolInfoV1Response>(instance);
        }


        /// <summary>
        /// Test the property 'TotalNetSpaceTiB'
        /// </summary>
        [Fact]
        public void TotalNetSpaceTiBTest()
        {
            // TODO unit test for the property 'TotalNetSpaceTiB'
        }
        /// <summary>
        /// Test the property 'PoolNetSpaceTiB'
        /// </summary>
        [Fact]
        public void PoolNetSpaceTiBTest()
        {
            // TODO unit test for the property 'PoolNetSpaceTiB'
        }
        /// <summary>
        /// Test the property 'NaPoolNetSpaceTiB'
        /// </summary>
        [Fact]
        public void NaPoolNetSpaceTiBTest()
        {
            // TODO unit test for the property 'NaPoolNetSpaceTiB'
        }
        /// <summary>
        /// Test the property 'EuPoolNetSpaceTiB'
        /// </summary>
        [Fact]
        public void EuPoolNetSpaceTiBTest()
        {
            // TODO unit test for the property 'EuPoolNetSpaceTiB'
        }
        /// <summary>
        /// Test the property 'AsiaPoolNetSpaceTiB'
        /// </summary>
        [Fact]
        public void AsiaPoolNetSpaceTiBTest()
        {
            // TODO unit test for the property 'AsiaPoolNetSpaceTiB'
        }
        /// <summary>
        /// Test the property 'TotalActiveFarms'
        /// </summary>
        [Fact]
        public void TotalActiveFarmsTest()
        {
            // TODO unit test for the property 'TotalActiveFarms'
        }
        /// <summary>
        /// Test the property 'EstimatedTimeToWinSeconds'
        /// </summary>
        [Fact]
        public void EstimatedTimeToWinSecondsTest()
        {
            // TODO unit test for the property 'EstimatedTimeToWinSeconds'
        }
        /// <summary>
        /// Test the property 'MinimumPayoutBalanceInXCH'
        /// </summary>
        [Fact]
        public void MinimumPayoutBalanceInXCHTest()
        {
            // TODO unit test for the property 'MinimumPayoutBalanceInXCH'
        }

    }

}
