/*
 * Space Pool Developer API
 *
 * Space Pool public developer REST APIs
 *
 * The version of the OpenAPI document: v1
 * Contact: info@pool.space
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpacePoolMonitor.ApiClient.Api;
using SpacePoolMonitor.ApiClient.Model;
using SpacePoolMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SpacePoolMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RewardV1Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RewardV1ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RewardV1Model
        //private RewardV1Model instance;

        public RewardV1ModelTests()
        {
            // TODO uncomment below to create an instance of RewardV1Model
            //instance = new RewardV1Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RewardV1Model
        /// </summary>
        [Fact]
        public void RewardV1ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RewardV1Model
            //Assert.IsType<RewardV1Model>(instance);
        }


        /// <summary>
        /// Test the property 'RewardDateTimeUtc'
        /// </summary>
        [Fact]
        public void RewardDateTimeUtcTest()
        {
            // TODO unit test for the property 'RewardDateTimeUtc'
        }
        /// <summary>
        /// Test the property 'SharePercent'
        /// </summary>
        [Fact]
        public void SharePercentTest()
        {
            // TODO unit test for the property 'SharePercent'
        }
        /// <summary>
        /// Test the property 'RewardInMojo'
        /// </summary>
        [Fact]
        public void RewardInMojoTest()
        {
            // TODO unit test for the property 'RewardInMojo'
        }
        /// <summary>
        /// Test the property 'FeesWithheldInMojo'
        /// </summary>
        [Fact]
        public void FeesWithheldInMojoTest()
        {
            // TODO unit test for the property 'FeesWithheldInMojo'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }

    }

}
